// src/app/[locale]/layout.tsx
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { ThemeProvider } from 'next-themes';
import { hasLocale } from 'next-intl';
import { notFound } from 'next/navigation';
import { routing } from '@/i18n/routing';
import '../globals.css';
import { Metadata } from 'next';
import AuthProvider from '../providers/auth-provider';
import { Toaster } from "sonner";
import { inter } from '@/components/fonts';
import PWAInstallButton from '@/components/PWAInstallButton';


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
    manifest: "/manifest.json", // this is for pwa
};

export function generateStaticParams() {
    return routing.locales.map((locale) => ({ locale }));
}

export default async function LocaleLayout({
    children,
    params
}: {
    children: React.ReactNode;
    params: Promise<{ locale: string }>;
}) {
    const { locale } = await params;

    if (!hasLocale(routing.locales, locale)) {
        notFound();
    }

    const messages = await getMessages();

    return (
        <html lang={locale} suppressHydrationWarning>
            
            <body className={`${inter.className} antialiased`}>
                <NextIntlClientProvider messages={messages}>
                    <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
                        <AuthProvider>
                            {children}
                        </AuthProvider>
                        <Toaster position="top-right" richColors /> {/* optional props */}
                    </ThemeProvider>
                </NextIntlClientProvider>
                <PWAInstallButton />
            </body>
        </html>
    );
}